backend:
  name: github
  repo: caoxian0827/travelchina.pro
  branch: main
  auth_endpoint: auth
  base_url: https://api.netlify.com
  client_id: 您的GitHub OAuth Client ID

# 媒体文件存储位置
media_folder: "images/uploads"
public_folder: "/images/uploads"

# 媒体库设置
media_library:
  name: uploadcare
  config:
    publicKey: 公共密钥（可选）

# 内容集合定义
collections:
  - name: "pages"
    label: "页面"
    files:
      - name: "home"
        label: "首页"
        file: "index.html"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}
      
      - name: "about"
        label: "关于页面"
        file: "about.html"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}

  - name: "destinations"
    label: "目的地"
    folder: "/"
    create: true
    filter: {field: "contentType", value: "destination"}
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容类型", name: "contentType", widget: "hidden", default: "destination"}
      - {label: "目的地简介", name: "description", widget: "text"}
      - {label: "封面图片", name: "thumbnail", widget: "image"}
      - {label: "内容", name: "body", widget: "markdown"}
