backend:
  name: github
  repo: caoxian0827/travelchina.pro
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "页面"
    files:
      - name: "home"
        label: "首页"
        file: "index.html"
        fields:
          - {label: "标题", name: "title", widget: "string"}
