   backend:
     name: git-gateway
     branch: main  # 或master，取决于您的主分支名称

   # 媒体文件存储位置
   media_folder: "images/uploads"
   public_folder: "/images/uploads"

   # 内容集合定义
   collections:
     - name: "pages"
       label: "页面"
       files:
         - name: "home"
           label: "首页"
           file: "index.html"
           fields:
             - {label: "标题", name: "title", widget: "string"}
             - {label: "内容", name: "body", widget: "markdown"}
         
         - name: "about"
           label: "关于页面"
           file: "about.html"
           fields:
             - {label: "标题", name: "title", widget: "string"}
             - {label: "内容", name: "body", widget: "markdown"}

     - name: "destinations"
       label: "目的地"
       folder: "/"
       create: true
       extension: "html"
       fields:
         - {label: "标题", name: "title", widget: "string"}
         - {label: "目的地简介", name: "description", widget: "text"}
         - {label: "内容", name: "body", widget: "markdown"}
